### ISSUE TITLE
C++ references are not supported?

### ISSUE THREAD

**Issue by jbreitbart** [lrr-tum/dbrew#23]
The following code results in a segmentation fault:

```
#include "dbrew.h"
int foo(const int &i, int j)
{
  if (i == 5) return 0;
  return i+j;
}

typedef int (*foo_t)(const int&, int);

int main(int argc, char* argv[])
{
  Rewriter* r = dbrew_new();
  dbrew_verbose(r, true, true, true);
  dbrew_set_function(r, (uint64_t) foo);
  dbrew_config_staticpar(r, 0);
  dbrew_config_parcount(r, 2);
  foo_t f = (foo_t) dbrew_rewrite(r, 2, 3);
  return f(2, 3);
}
```

Error log is here: https://gist.github.com/jbreitbart/06f36029e4d42ec9900f3d6a9868ff1a

**Comment by weidendo** [comment]
Interesting. DBrew has a C API, and you try to use it with C++ calling conventions with references.
C++ functions expect pointers passed for references, but "dbrew_rewrite" gets values 2 and 3 passed. Then the rewriting crashes when it dereferences address 2.

First, rewriting never should crash. As such, when accessing memory in emulation, we should catch any segmentation faults (or check the address before against /proc/self/maps). But this does not handle this issue.

"dbrew_rewrite" currently has the signature "uint64_t dbrew_rewrite(Rewriter* r, ...);". To make
the compiler call the rewriter as needed for references, we need to cast dbrew_rewrite
to have the correct signature.

```
typedef int64_t (*rewrite_foo_t)(Rewriter*, const int&, int);
...
foo_t f = (foo_t) ((rewrite_foo_t)dbrew_rewrite)(r, 2, 3);
```

Then it works as expected .-) This is due to pointer parameters marked as known also mark all values dereferenced beyond the pointer as known. And a C++ reference is a pointer parameter in binary code.

I see that the DBrew C API is not easy to use from C++, but at least it works if used correctly.
Does it help if we change the dbrew_rewrite function to allow to be casted to the same signature as the
function to be rewritten? Then the Rewriter object has to be passed by a global variable.
We would have something like

```
foot_t f = (foo_t) ((foo_t) dbrew_rewrite)(2,3);
```

Not sure this is any better.
But we may need to do this anyway, as then the rewriter does not explicitly has to know the number of parameters: we could remove the need for calling dbrew_config_parcount().

**Comment by weidendo** [comment]
Added some documentation about that [here](https://github.com/lrr-tum/dbrew/blob/master/docs/C%2B%2B.md).
